# This file can be copied into ~/.config/kitty/
hostname <whatever>

# Copy zsh ricing files
env ZDOTDIR=$HOME
copy --dest .zshrc path/to/.zshrc
copy --dest .antigenrc path/to/.antigenrc
copy --dest .zsh path/to/.zsh

# Copy vim ricing files
copy --dest .vimrc path/to/.vimrc
copy --dest .vim path/to/.vim

# Color theme in remote shell
color_scheme Base2Tone Drawbridge Dark
