- name: Install dotfiles
  hosts: all
  become: yes # this means root access !

  vars:
    users:
      - name: admin #default user created with cloud-init when a new VM is initialized
        home: /home/admin
      - name: root
        home: /root

  tasks:
    - name: Update packages
      ansible.builtin.apt:
        pkg:
        - vim
        - zsh
        state: present

    - name: Check users' default shell
      ansible.builtin.command: echo $0
      loop: "{{ users }}"
      register: output

    - name: Make zsh default shell
      ansible.builtin.command: chsh -s /usr/bin/zsh {{ item.name }}
      loop: "{{ users }}"
      changed_when: output == -bash

    - name: Git clone my dotfiles
      ansible.builtin.git:
        repo: "https://git.timewire.fr/torineos/lightweight-dotfiles.git"
        path: "{{ users.home }}"
      loop: "{{ users }}"
